# Generated by Django 4.1.5 on 2023-02-23 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_faculty_university_video_worker_delete_bicycle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='university_id',
            new_name='university',
        ),
    ]
