# Generated by Django 4.1.5 on 2023-02-23 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_image_src_remove_university_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image_src',
        ),
    ]
