# Generated by Django 4.1.5 on 2023-02-23 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_image_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.university'),
        ),
        migrations.AlterField(
            model_name='image_src',
            name='image_scr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image_src',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.university'),
        ),
        migrations.AlterField(
            model_name='university',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='university',
            name='living',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_src',
            field=models.TextField(blank=True, null=True),
        ),
    ]
