# Generated by Django 4.1.5 on 2023-02-24 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_alter_faculty_university_alter_image_src_image_scr_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image_src',
        ),
    ]
