# Generated by Django 4.1.5 on 2023-02-24 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_image_src'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image_src',
        ),
    ]
