# Generated by Django 4.1.5 on 2023-02-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_image_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_src',
            name='image_scr',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
