# Generated by Django 4.1.5 on 2023-02-25 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_remove_university_language_remove_university_living_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image_src',
        ),
    ]
