# Generated by Django 4.1.5 on 2023-03-03 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_image_src'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image_src',
        ),
    ]
