# Generated by Django 4.1.5 on 2023-03-03 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_alter_image_src_image_scr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='university',
        ),
        migrations.AddField(
            model_name='university',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.faculty'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='photo_src',
            field=models.ImageField(upload_to='static/managers'),
        ),
    ]
