# Generated by Django 4.1.5 on 2023-03-03 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_image_src_first_image_src_second'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_src',
            name='image_scr',
        ),
    ]
