# Generated by Django 4.1.5 on 2023-03-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_remove_image_src_image_scr'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_src',
            name='image_scr',
            field=models.TextField(default='images/1_first.png'),
        ),
    ]
