# Generated by Django 4.1.5 on 2023-03-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0023_image_src_image_scr'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='city',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
