# Generated by Django 4.1.5 on 2023-03-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0025_university_rating_university_structure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='rating',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='structure',
            field=models.TextField(blank=True, null=True),
        ),
    ]
