# Generated by Django 4.1.5 on 2023-03-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0028_remove_university_faculty_faculty_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('country', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=20)),
                ('school_class', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
