# Generated by Django 4.1.5 on 2023-03-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0029_client_forms_delete_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_forms',
            name='number',
            field=models.CharField(default='none2', max_length=12),
        ),
        migrations.AlterField(
            model_name='client_forms',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
